# 使用 nginx 官方 alpine 镜像
FROM crpi-wl49qzscz2duphdo.cn-qingdao.personal.cr.aliyuncs.com/iuufu-erp-prod/nginx:1.26.3-alpine-perl

# 设置工作目录
WORKDIR /usr/share/nginx/html

# 清理默认静态文件
RUN rm -rf ./*

# 拷贝前端构建文件
COPY .output/public ./

# 拷贝配置文件
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf

# 拷贝 SSL 证书
COPY www.erp.iuufu.com.pem /etc/nginx/ssl/www.erp.iuufu.com.pem
COPY www.erp.iuufu.com.key /etc/nginx/ssl/www.erp.iuufu.com.key

# 设置私钥权限
RUN chmod 600 /etc/nginx/ssl/www.erp.iuufu.com.key && \
    chown root:root /etc/nginx/ssl/www.erp.iuufu.com.key

# 暴露 HTTP 和 HTTPS 端口
EXPOSE 90

# 启动 nginx
CMD ["nginx", "-g", "daemon off;"]